name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: stable
          # Cache is managed by golangci-lint
          # https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=5m --config=.golangci.yaml
          version: latest
          working-directory: .
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: actions/checkout@v3
      - name: Run tests with coverage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
